apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-alert-injector
  namespace: demo
  labels:
    app: api
    fault: alert-injector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
      fault: alert-injector
  template:
    metadata:
      labels:
        app: api
        fault: alert-injector
    spec:
      containers:
        - name: api
          image: w9-api:1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: ERROR_RATE
              value: "1"
            - name: VERSION
              value: "alert-injector"
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
